apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: my_htpasswd_provider
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret
  - name: MS_AD
    challenge: true
    login: true
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id: ["sAMAccountName"]
        email: ["mail"]
        name: ["displayName"]
        preferredUsername: ["sAMAccountName"]
      bindDN: "CN=ocpbind,CN=Users,DC=sample,DC=org"
      bindPassword:
        name: ldap-secret
      insecure: false
      ca:
        name: ca-config-map
        #url: "ldaps://sample-dc01.sample.org:636/cn=users,dc=sample,dc=org?uid?sub?(memberOf=cn=ocp-users,cn=users,dc=sample,dc=org)"
      url: "ldaps://sample-dc01.sample.org:636/CN=Users,DC=sample,DC=org?sAMAccountName?sub?(objectClass=user)"
